### ISSUE TITLE
No responde adecuadamente con el scroll del mouse

### ISSUE THREAD

**Issue by xcesaralejandro** [jjcosgrove/jquery-aniview#12]
Cuando cargo la pagina directamente en una sección que posea aniview o utilice el scroll del navegador las animaciones funcionan correctamente. Sin embargo, cuando utilizo el scroll del mouse para descender en la pagina hasta una sección que posea animaciones, estas responden en 3s aproximadamente (Lo que deja la pagina sin el contenido durante esos 3s) si durante esos 3 segundos hago un click en la pagina la animación se activa, pero si solo voy bajando con el scroll del mouse sin hacer click en la pagina estas se activan luego de un rato (Lo que da la sensación de que en el sitio web no hay contenido o demora en cargar) ¿Como puedo resolver eso?

**Comment by xcesaralejandro** [comment]
Es la versión de **JQuery, no funciona con v3.2.1**, Espero puedas actualizarlo pronto :)

**Comment by jjcosgrove** [comment]
hi @xcesaralejandro 

I have created a fiddle for you which shows this working, fine?

jQuery: 3.2.1
Animate.css: 3.5.2

https://jsfiddle.net/gnooL3ew/7/

I wonder if your issues are either relating to another plugin on the page, or perhaps your threshold is too low? (you can set this via the configuration object for AniView)

If you can provide a fiddle with your code on to help replicate the error I will investigate further.

```js
var options = {
    animateThreshold: 100,
    scrollPollInterval: 20
}
$('.aniview').AniView(options);
```

*** Translated ***

Hola @xcesaralejandro

He creado un violín para ti que muestra que funciona, ¿está bien?

jQuery: 3.2.1
Animate.css: 3.5.2

https://jsfiddle.net/gnooL3ew/7/

Me pregunto si sus problemas están relacionados con otro complemento en la página, o tal vez su umbral es demasiado bajo. (puede configurar esto a través del objeto de configuración para AniView)

Si puede proporcionar un violín con su código para ayudar a replicar el error, lo investigaré más a fondo.

```js
var options = {
    animateThreshold: 100,
    scrollPollInterval: 20
}
$('.aniview').AniView(options);
```

**Comment by xcesaralejandro** [comment]
**JQuery v3.2.1** (He probado con la versión v2.1.3 que es la que usas en http://jjcosgrove.github.io/jquery-aniview/ y funciona correctamente).


Aparte de aniview sólo estoy utilizando:
- Jquery
- Materialize

Grabé un vídeo para que puedas aprecias mejor el problema, le he puesto comentarios en ingles para que los puedas leer más fácil (Pero mi ingles es muy básico):

https://www.youtube.com/watch?v=CqgkMFcMtV8


Orden en que cargo los script
`<script src="js/jquery.js"></script>
    <script src="js/materialize.min.js"></script>
    <script src="js/jquery.aniview.js"></script>`

Como llamo a la animación:
`<div class="card aniview" data-av-animation="jackInTheBox">`

Todo el js que utilizo:
`<script>
        $(document).ready(function() {
            $(".button-collapse").sideNav();
            $('.slider').slider();
            Materialize.updateTextFields();
            $('#mensaje').val('New Text');
            $('#mensaje').trigger('autoresize');
            $('select').material_select();
            $('.modal').modal();
            $('#modal1').modal('open');
            $('#modal1').modal('close');

            // Ajax to form
            $('#form_contacto').on('submit', function(e) {
                e.preventDefault();
                fml = $('#form_contacto').attr('action');
                mt = $('#form_contacto').attr('method');
                $.ajax({
                    beforeSend: function() {
                        $('#mensaje_send_form').empty();
                        $('#load_send_form').css('display', 'block');
                    },
                    url: fml,
                    type: mt,
                    data: $('#form_contacto').serialize(),
                    success: function(resp) {
                        if (resp == 'Ok') {
                            $('#mensaje_send_form').append('<span style="color: green;">Mensaje enviado correctamente.</span>');
                        } else if (resp == 'Error') {
                            $('#mensaje_send_form').append('<span style="color: red;">El mensaje no ha podido ser enviado, puede enviar un correo manualmente a: staff@bouceto.cl </span>');
                        }
                    },
                    error: function(jqXHR, estado, error) {
                        $('#mensaje_send_form').append('<span style="color: red;">Error,' + estado + ' - ' + error + '</span>');
                    },
                    complete: function() {
                        $('#load_send_form').css('display', 'none');
                    },
                    timeout: 10000
                });
            });

            // ScrollTo
            $('nav a').on('click',function(e){
              e.preventDefault();
              var ctx = $(this);
              var link = ctx.attr('href');
              console.log(link);
              $('html').animate({
                scrollTop: $(link).offset().top
              },1000);
            });

            // aniview
            $('.aniview').AniView({
              animateThreshold: 250,
              scrollPollInterval: 50
            });


        }); //END JQuery load 
    </script>`

**Comment by jjcosgrove** [comment]
Nice website! 👍 

I have taken your code and placed it here with a few modifications:

https://jsfiddle.net/70why7ra/

This appears to work fine? One thing I did notice, is that the 'jackInTheBox' animation does not appear to be included in the NPM package for 3.5.2 of animate.css?

https://github.com/daneden/animate.css/issues/737

If you see my jsfiddle above you will notice that I have added that code:

```css
.jackInTheBox {
          animation-name: jackInTheBox
      }
      @keyframes jackInTheBox {
          0% {
              opacity: 0;
              transform: scale(.1) rotate(30deg);
              transform-origin: center bottom
          }
          50% {
              transform: rotate(-10deg)
          }
          70% {
              transform: rotate(3deg)
          }
          to {
              opacity: 1;
              transform: scale(1)
          }
      }
```

which then allows to use that animation. Both of the jsfiddle demos I have so far provided; showing AniView working, included jquery 3.2.1. Can you please therefore try the following:

1. Re-check you are using the latest versions of jQuery, AniView and animate.css
2. Add the missing 'jackInTheBox' css if needed.
3. Remove ALL javascript that does not relate to the animated boxes, including the <script> tags etc... e.g. materialize?

I wonder if something else on the page is intercepting the events and not propagating them until you 'click' on the page?

*** Translation ***

Buen sitio web! 👍

Tomé su código y lo coloqué aquí con algunas modificaciones:

https://jsfiddle.net/70why7ra/

Esto parece funcionar bien? Una cosa que noté, es que la animación 'jackInTheBox' no parece estar incluida en el paquete de NPM para 3.5.2 de animate.css?

https://github.com/daneden/animate.css/issues/737

Si ve mi jsfiddle arriba, notará que he agregado ese código:

```css
.jackInTheBox {
          nombre-animación: jackInTheBox
      }
      @keyframes jackInTheBox {
          0% {
              opacidad: 0;
              transformar: escala (.1) rotar (30deg);
              origen transformado: centro inferior
          }
          50% {
              transformar: rotar (-10deg)
          }
          70% {
              transformar: rotar (3deg)
          }
          a {
              opacidad: 1;
              transformar: escala (1)
          }
      }
```

que luego permite usar esa animación. Las dos demos de jsfiddle que he proporcionado hasta ahora; mostrando el funcionamiento de AniView, incluido jquery 3.2.1. Por lo tanto, puede intentar lo siguiente:

1. Vuelva a verificar que está utilizando las últimas versiones de jQuery, AniView y animate.css
2. Agregue el css 'jackInTheBox' que falta si es necesario.
3. Elimine TODO el javascript que no esté relacionado con los cuadros animados, incluidas las etiquetas <script>, etc ... p. Ej. ¿materializar?

Me pregunto si hay algo más en la página que intercepte los eventos y no los propague hasta que haga clic en la página.
